#ifndef __DEFINES_H_
#define __DEFINES_H_

#define FC __fastcall

#define FIGHTER 0
#define BOSS1   0
#define BOSS2   0

#define FIGHTERWIDTH 80
#define FIGHTERHEIGHT 50

#define BOSS1WIDTH 250
#define BOSS1HEIGHT 150

#define BOSS2WIDTH 250
#define BOSS2HEIGHT 150

#define ENEMYWIDTH 50
#define ENEMYHEIGHT 60

#define ENEMY5WIDTH 36
#define ENEMY5HEIGHT 34

#define ENEMY6WIDTH 75
#define ENEMY6HEIGHT 60

#define ENEMY7WIDTH 60
#define ENEMY7HEIGHT 50

#define TANKWIDTH 50
#define TANKHEIGHT 50

#define BULLETWIDTH 15
#define BULLETHEIGHT 15

#define ROCKETWIDTH 10
#define ROCKETHEIGHT 20

#define POWERUPWIDTH 30
#define POWERUPHEIGHT 30

#define CLOUDWIDTH 90
#define CLOUDHEIGHT 40

#define FIGHTERINTERRUPT 1
#define CLOUDTIMER 3
#define GAMECLOCK 2
#define EXTRAWAVE 4
#define TANKINTERRUPT 5
#define MUSICINTERRUPT 6

#define GAMESPEED 2000

#endif